### ISSUE TITLE
Adding Caching to improve performance in case of repeated searches in the same issue

### ISSUE THREAD

**Issue by Tarun047** [serhii73/find_the_site#14]
Current implementation computes search results again and again even though the search parameter is same.
I think we could gain a performance improvement in the code if we could cache the search results per session. (ie. per import).
I have run a simple timing on the module without caching and with caching and we can see that with caching the result is so much better
![pic](https://user-images.githubusercontent.com/32017154/66470579-7aab5e80-eaa7-11e9-9c2f-7eb4212c0f50.png)

**Comment by Tarun047** [comment]
Assign me to the issue and I can enable caching.

**Comment by serhii73** [comment]
Thank you very much!
