### ISSUE TITLE
URL return broken

### ISSUE THREAD

**Issue by roshansridhar** [serhii73/find_the_site#19]
the 'get_website' function from find_the_site.fw is returning 'duckduckgo.com' for many searches. Could you please fix this?

**Comment by serhii73** [comment]
Hi @roshansridhar 
Could you please show your snippet?
Thank you :)

**Comment by roshansridhar** [comment]
`from find_the_site.fw import get_website`
`get_website("hello world")`

You might have to try it multiple times

**Comment by roshansridhar** [comment]
![Screen Shot 2020-02-06 at 11 24 59 AM](https://user-images.githubusercontent.com/25312138/74344057-039a1580-4d7a-11ea-94de-f4c9cd8b7a2b.png)
@serhii73 for reference. This shows up multiple times on the top. It seems like the layout for the website is now different

**Comment by serhii73** [comment]
Thank you very much @roshansridhar 
But, right now I don't have enough time to the improvement of this library.
If you want you can send me PR to resolve this problem.
Thanks :)

**Comment by roshansridhar** [comment]
I've just sent one! :)

**Comment by serhii73** [comment]
Thank you.
I will review it.
Thanks again.

**Comment by roshansridhar** [comment]
Hey, you should give this a review, it works 👍

**Comment by serhii73** [comment]
@roshansridhar I merged your PR but the library doesn't work with DDG right now.
It's working only with ecosia.org

**Comment by serhii73** [comment]
Thank you very much for your PR, I am going to close this issue.
