### ISSUE TITLE
Return list instead first element

### ISSUE THREAD

**Issue by serhii73** [serhii73/find_the_site#2]
Return `website_list` instead `website` 
https://github.com/serhii73/find_the_site/blob/master/find_the_site/fw.py

**Comment by robflop** [comment]
I've submitted a PR for this at #6.

**Comment by sanav33** [comment]
I could work on this if it's still open.

**Comment by serhii73** [comment]
> I could work on this if it's still open.

Sorry. @robflop was first.
You can take other issues from my projects.
For example, from here https://github.com/serhii73/place2live
